// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.27.2
// source: product.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_AddProducts_FullMethodName     = "/pb.Service/AddProducts"
	Service_UpdateProducts_FullMethodName  = "/pb.Service/UpdateProducts"
	Service_DelProducts_FullMethodName     = "/pb.Service/DelProducts"
	Service_GetProductsById_FullMethodName = "/pb.Service/GetProductsById"
	Service_SearchProducts_FullMethodName  = "/pb.Service/SearchProducts"
	Service_NotifyPay_FullMethodName       = "/pb.Service/NotifyPay"
	Service_CreateOrder_FullMethodName     = "/pb.Service/CreateOrder"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// -----------------------products-----------------------
	AddProducts(ctx context.Context, in *AddProductsReq, opts ...grpc.CallOption) (*AddProductsResp, error)
	UpdateProducts(ctx context.Context, in *UpdateProductsReq, opts ...grpc.CallOption) (*UpdateProductsResp, error)
	DelProducts(ctx context.Context, in *DelProductsReq, opts ...grpc.CallOption) (*DelProductsResp, error)
	GetProductsById(ctx context.Context, in *GetProductsByIdReq, opts ...grpc.CallOption) (*GetProductsByIdResp, error)
	SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error)
	NotifyPay(ctx context.Context, in *NotifyPayReq, opts ...grpc.CallOption) (*NotifyPayResp, error)
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) AddProducts(ctx context.Context, in *AddProductsReq, opts ...grpc.CallOption) (*AddProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProductsResp)
	err := c.cc.Invoke(ctx, Service_AddProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpdateProducts(ctx context.Context, in *UpdateProductsReq, opts ...grpc.CallOption) (*UpdateProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductsResp)
	err := c.cc.Invoke(ctx, Service_UpdateProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DelProducts(ctx context.Context, in *DelProductsReq, opts ...grpc.CallOption) (*DelProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelProductsResp)
	err := c.cc.Invoke(ctx, Service_DelProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetProductsById(ctx context.Context, in *GetProductsByIdReq, opts ...grpc.CallOption) (*GetProductsByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsByIdResp)
	err := c.cc.Invoke(ctx, Service_GetProductsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SearchProducts(ctx context.Context, in *SearchProductsReq, opts ...grpc.CallOption) (*SearchProductsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResp)
	err := c.cc.Invoke(ctx, Service_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) NotifyPay(ctx context.Context, in *NotifyPayReq, opts ...grpc.CallOption) (*NotifyPayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyPayResp)
	err := c.cc.Invoke(ctx, Service_NotifyPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, Service_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	// -----------------------products-----------------------
	AddProducts(context.Context, *AddProductsReq) (*AddProductsResp, error)
	UpdateProducts(context.Context, *UpdateProductsReq) (*UpdateProductsResp, error)
	DelProducts(context.Context, *DelProductsReq) (*DelProductsResp, error)
	GetProductsById(context.Context, *GetProductsByIdReq) (*GetProductsByIdResp, error)
	SearchProducts(context.Context, *SearchProductsReq) (*SearchProductsResp, error)
	NotifyPay(context.Context, *NotifyPayReq) (*NotifyPayResp, error)
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) AddProducts(context.Context, *AddProductsReq) (*AddProductsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProducts not implemented")
}
func (UnimplementedServiceServer) UpdateProducts(context.Context, *UpdateProductsReq) (*UpdateProductsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProducts not implemented")
}
func (UnimplementedServiceServer) DelProducts(context.Context, *DelProductsReq) (*DelProductsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelProducts not implemented")
}
func (UnimplementedServiceServer) GetProductsById(context.Context, *GetProductsByIdReq) (*GetProductsByIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductsById not implemented")
}
func (UnimplementedServiceServer) SearchProducts(context.Context, *SearchProductsReq) (*SearchProductsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedServiceServer) NotifyPay(context.Context, *NotifyPayReq) (*NotifyPayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPay not implemented")
}
func (UnimplementedServiceServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_AddProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AddProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AddProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AddProducts(ctx, req.(*AddProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpdateProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpdateProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UpdateProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpdateProducts(ctx, req.(*UpdateProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DelProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DelProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_DelProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DelProducts(ctx, req.(*DelProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetProductsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetProductsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetProductsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetProductsById(ctx, req.(*GetProductsByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SearchProducts(ctx, req.(*SearchProductsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_NotifyPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).NotifyPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_NotifyPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).NotifyPay(ctx, req.(*NotifyPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProducts",
			Handler:    _Service_AddProducts_Handler,
		},
		{
			MethodName: "UpdateProducts",
			Handler:    _Service_UpdateProducts_Handler,
		},
		{
			MethodName: "DelProducts",
			Handler:    _Service_DelProducts_Handler,
		},
		{
			MethodName: "GetProductsById",
			Handler:    _Service_GetProductsById_Handler,
		},
		{
			MethodName: "SearchProducts",
			Handler:    _Service_SearchProducts_Handler,
		},
		{
			MethodName: "NotifyPay",
			Handler:    _Service_NotifyPay_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Service_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
