// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: product.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------products--------------------------------
type Products struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            //id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         //鍟嗗搧鍚嶇О
	Subtitle      string                 `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"` //鍓爣棰?  string desc = 7; //鍟嗗搧鎻忚堪
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`         //鍓爣棰?  string desc = 7; //鍟嗗搧鎻忚堪
	Images        string                 `protobuf:"bytes,5,opt,name=images,proto3" json:"images,omitempty"`     //鍟嗗搧鍥剧墖(JSON鏁扮粍)
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`     //褰撳墠浠锋牸
	Stock         int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`      //搴撳瓨鏁伴噺
	Status        int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`    //鐘舵€? 0-涓嬫灦, 1-涓婃灦, 2-鍒犻櫎
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Products) Reset() {
	*x = Products{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Products) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Products) ProtoMessage() {}

func (x *Products) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Products.ProtoReflect.Descriptor instead.
func (*Products) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Products) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Products) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Products) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Products) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Products) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *Products) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Products) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Products) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         //鍟嗗搧鍚嶇О
	Subtitle      string                 `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"` //鍓爣棰?  string desc = 3; //鍟嗗搧鎻忚堪
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`         //鍓爣棰?  string desc = 3; //鍟嗗搧鎻忚堪
	Images        string                 `protobuf:"bytes,4,opt,name=images,proto3" json:"images,omitempty"`     //鍟嗗搧鍥剧墖(JSON鏁扮粍)
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`     //褰撳墠浠锋牸
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`      //搴撳瓨鏁伴噺
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`    //鐘舵€? 0-涓嬫灦, 1-涓婃灦, 2-鍒犻櫎
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsReq) Reset() {
	*x = AddProductsReq{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsReq) ProtoMessage() {}

func (x *AddProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsReq.ProtoReflect.Descriptor instead.
func (*AddProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductsReq) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *AddProductsReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AddProductsReq) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *AddProductsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddProductsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductsReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsResp) Reset() {
	*x = AddProductsResp{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsResp) ProtoMessage() {}

func (x *AddProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsResp.ProtoReflect.Descriptor instead.
func (*AddProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *AddProductsResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            //id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         //鍟嗗搧鍚嶇О
	Subtitle      string                 `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"` //鍓爣棰?  string desc = 4; //鍟嗗搧鎻忚堪
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`         //鍓爣棰?  string desc = 4; //鍟嗗搧鎻忚堪
	Images        string                 `protobuf:"bytes,5,opt,name=images,proto3" json:"images,omitempty"`     //鍟嗗搧鍥剧墖(JSON鏁扮粍)
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`     //褰撳墠浠锋牸
	Stock         int64                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`      //搴撳瓨鏁伴噺
	Status        int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`    //鐘舵€? 0-涓嬫灦, 1-涓婃灦, 2-鍒犻櫎
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsReq) Reset() {
	*x = UpdateProductsReq{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsReq) ProtoMessage() {}

func (x *UpdateProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsReq.ProtoReflect.Descriptor instead.
func (*UpdateProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductsReq) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *UpdateProductsReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateProductsReq) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *UpdateProductsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductsReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductsReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsResp) Reset() {
	*x = UpdateProductsResp{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsResp) ProtoMessage() {}

func (x *UpdateProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsResp.ProtoReflect.Descriptor instead.
func (*UpdateProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductsResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelProductsReq) Reset() {
	*x = DelProductsReq{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelProductsReq) ProtoMessage() {}

func (x *DelProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelProductsReq.ProtoReflect.Descriptor instead.
func (*DelProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *DelProductsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelProductsResp) Reset() {
	*x = DelProductsResp{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelProductsResp) ProtoMessage() {}

func (x *DelProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelProductsResp.ProtoReflect.Descriptor instead.
func (*DelProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *DelProductsResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductsByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIdReq) Reset() {
	*x = GetProductsByIdReq{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIdReq) ProtoMessage() {}

func (x *GetProductsByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIdReq.ProtoReflect.Descriptor instead.
func (*GetProductsByIdReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductsByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductsByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      *Products              `protobuf:"bytes,1,opt,name=products,proto3" json:"products,omitempty"` //products
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIdResp) Reset() {
	*x = GetProductsByIdResp{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIdResp) ProtoMessage() {}

func (x *GetProductsByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIdResp.ProtoReflect.Descriptor instead.
func (*GetProductsByIdResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductsByIdResp) GetProducts() *Products {
	if x != nil {
		return x.Products
	}
	return nil
}

type SearchProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`     //page
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`     //size
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`         //id
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`      //鍟嗗搧鍚嶇О
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` //鐘舵€? 0-涓嬫灦, 1-涓婃灦, 2-鍒犻櫎
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsReq) Reset() {
	*x = SearchProductsReq{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsReq) ProtoMessage() {}

func (x *SearchProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsReq.ProtoReflect.Descriptor instead.
func (*SearchProductsReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *SearchProductsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchProductsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchProductsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchProductsReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SearchProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Products            `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"` //products
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResp) Reset() {
	*x = SearchProductsResp{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResp) ProtoMessage() {}

func (x *SearchProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResp.ProtoReflect.Descriptor instead.
func (*SearchProductsResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *SearchProductsResp) GetProducts() []*Products {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`        //用户ID
	PayType       int64                  `protobuf:"varint,2,opt,name=payType,proto3" json:"payType,omitempty"`      //支付方式,0-支付宝,1-微信
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`    //购买数量
	OrderItems    []*OrderItem           `protobuf:"bytes,4,rep,name=orderItems,proto3" json:"orderItems,omitempty"` //订单商品项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *CreateOrderReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderReq) GetOrderItems() []*OrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`     //商品ID
	ProductId     int64                  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"` //商品ID
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`   //购买数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *OrderItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"` //订单号
	Total         float32                `protobuf:"fixed32,2,opt,name=total,proto3" json:"total,omitempty"`   //订单总金额
	PayType       string                 `protobuf:"bytes,3,opt,name=payType,proto3" json:"payType,omitempty"` //支付方式,0-支付宝,1-微信
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrderResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderResp) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CreateOrderResp) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

type NotifyPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=orderNo,proto3" json:"orderNo,omitempty"` //订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPayReq) Reset() {
	*x = NotifyPayReq{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPayReq) ProtoMessage() {}

func (x *NotifyPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPayReq.ProtoReflect.Descriptor instead.
func (*NotifyPayReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyPayReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type NotifyPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPayResp) Reset() {
	*x = NotifyPayResp{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPayResp) ProtoMessage() {}

func (x *NotifyPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPayResp.ProtoReflect.Descriptor instead.
func (*NotifyPayResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\x02pb\"\xba\x01\n" +
	"\bProducts\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x16\n" +
	"\x06images\x18\x05 \x01(\tR\x06images\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\"\xb0\x01\n" +
	"\x0eAddProductsReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubtitle\x18\x02 \x01(\tR\bsubtitle\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x16\n" +
	"\x06images\x18\x04 \x01(\tR\x06images\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\"!\n" +
	"\x0fAddProductsResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc3\x01\n" +
	"\x11UpdateProductsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x16\n" +
	"\x06images\x18\x05 \x01(\tR\x06images\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\a \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\"$\n" +
	"\x12UpdateProductsResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\" \n" +
	"\x0eDelProductsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x0fDelProductsResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12GetProductsByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x13GetProductsByIdResp\x12(\n" +
	"\bproducts\x18\x01 \x01(\v2\f.pb.ProductsR\bproducts\"w\n" +
	"\x11SearchProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\">\n" +
	"\x12SearchProductsResp\x12(\n" +
	"\bproducts\x18\x01 \x03(\v2\f.pb.ProductsR\bproducts\"\x8d\x01\n" +
	"\x0eCreateOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\apayType\x18\x02 \x01(\x03R\apayType\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12-\n" +
	"\n" +
	"orderItems\x18\x04 \x03(\v2\r.pb.OrderItemR\n" +
	"orderItems\"_\n" +
	"\tOrderItem\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"[\n" +
	"\x0fCreateOrderResp\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x02R\x05total\x12\x18\n" +
	"\apayType\x18\x03 \x01(\tR\apayType\"(\n" +
	"\fNotifyPayReq\x12\x18\n" +
	"\aorderNo\x18\x01 \x01(\tR\aorderNo\"\x0f\n" +
	"\rNotifyPayResp\"E\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1e\n" +
	"\fRegisterResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xa9\x03\n" +
	"\aService\x126\n" +
	"\vAddProducts\x12\x12.pb.AddProductsReq\x1a\x13.pb.AddProductsResp\x12?\n" +
	"\x0eUpdateProducts\x12\x15.pb.UpdateProductsReq\x1a\x16.pb.UpdateProductsResp\x126\n" +
	"\vDelProducts\x12\x12.pb.DelProductsReq\x1a\x13.pb.DelProductsResp\x12B\n" +
	"\x0fGetProductsById\x12\x16.pb.GetProductsByIdReq\x1a\x17.pb.GetProductsByIdResp\x12?\n" +
	"\x0eSearchProducts\x12\x15.pb.SearchProductsReq\x1a\x16.pb.SearchProductsResp\x120\n" +
	"\tNotifyPay\x12\x10.pb.NotifyPayReq\x1a\x11.pb.NotifyPayResp\x126\n" +
	"\vCreateOrder\x12\x12.pb.CreateOrderReq\x1a\x13.pb.CreateOrderRespB\x04Z\x02./b\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_product_proto_goTypes = []any{
	(*Products)(nil),            // 0: pb.Products
	(*AddProductsReq)(nil),      // 1: pb.AddProductsReq
	(*AddProductsResp)(nil),     // 2: pb.AddProductsResp
	(*UpdateProductsReq)(nil),   // 3: pb.UpdateProductsReq
	(*UpdateProductsResp)(nil),  // 4: pb.UpdateProductsResp
	(*DelProductsReq)(nil),      // 5: pb.DelProductsReq
	(*DelProductsResp)(nil),     // 6: pb.DelProductsResp
	(*GetProductsByIdReq)(nil),  // 7: pb.GetProductsByIdReq
	(*GetProductsByIdResp)(nil), // 8: pb.GetProductsByIdResp
	(*SearchProductsReq)(nil),   // 9: pb.SearchProductsReq
	(*SearchProductsResp)(nil),  // 10: pb.SearchProductsResp
	(*CreateOrderReq)(nil),      // 11: pb.CreateOrderReq
	(*OrderItem)(nil),           // 12: pb.OrderItem
	(*CreateOrderResp)(nil),     // 13: pb.CreateOrderResp
	(*NotifyPayReq)(nil),        // 14: pb.NotifyPayReq
	(*NotifyPayResp)(nil),       // 15: pb.NotifyPayResp
	(*RegisterReq)(nil),         // 16: pb.RegisterReq
	(*RegisterResp)(nil),        // 17: pb.RegisterResp
}
var file_product_proto_depIdxs = []int32{
	0,  // 0: pb.GetProductsByIdResp.products:type_name -> pb.Products
	0,  // 1: pb.SearchProductsResp.products:type_name -> pb.Products
	12, // 2: pb.CreateOrderReq.orderItems:type_name -> pb.OrderItem
	1,  // 3: pb.Service.AddProducts:input_type -> pb.AddProductsReq
	3,  // 4: pb.Service.UpdateProducts:input_type -> pb.UpdateProductsReq
	5,  // 5: pb.Service.DelProducts:input_type -> pb.DelProductsReq
	7,  // 6: pb.Service.GetProductsById:input_type -> pb.GetProductsByIdReq
	9,  // 7: pb.Service.SearchProducts:input_type -> pb.SearchProductsReq
	14, // 8: pb.Service.NotifyPay:input_type -> pb.NotifyPayReq
	11, // 9: pb.Service.CreateOrder:input_type -> pb.CreateOrderReq
	2,  // 10: pb.Service.AddProducts:output_type -> pb.AddProductsResp
	4,  // 11: pb.Service.UpdateProducts:output_type -> pb.UpdateProductsResp
	6,  // 12: pb.Service.DelProducts:output_type -> pb.DelProductsResp
	8,  // 13: pb.Service.GetProductsById:output_type -> pb.GetProductsByIdResp
	10, // 14: pb.Service.SearchProducts:output_type -> pb.SearchProductsResp
	15, // 15: pb.Service.NotifyPay:output_type -> pb.NotifyPayResp
	13, // 16: pb.Service.CreateOrder:output_type -> pb.CreateOrderResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
